### ISSUE TITLE
curses causes issues in Windows

### ISSUE THREAD

**Issue by dweaver** [exosite/exoline#145]
In Windows after you manually install curses, this error appears:

```
$ exo twee 392b6246a09388507a003f99b6c1118b624020d1
Traceback (most recent call last):
  File "c:/Python27/Scripts/exo", line 77, in <module>
    import blessings
  File "c:\Python27\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ImportError: No module named fcntl
```

**Comment by dweaver** [comment]
@asolz would it hurt anything to pull blessings out?

**Comment by asolz** [comment]
No it wouldn't hurt to pull blessings out.

 A better solution might be to conditionally import blessings if the platform isn't Windows since right now windows users don't have any color.

https://github.com/exosite/exoline/blob/9fa4aa74305d8bc5437dfe1871abf22ce1129ef0/exoline/exo.py#L2019

Right now it's failing when it tries to import something that it won't even end up using.
